apiVersion: 1

datasources:
  - name: MySQL
    uid: mysql-minms
    type: mysql
    access: proxy
    isDefault: true
    url: mysql:3306
    user: root
    jsonData:
      database: minms
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
    secureJsonData:
      password: root
    editable: true

  - name: Redis
    uid: redis-minms
    type: redis-datasource
    access: proxy
    url: redis:6379
    jsonData:
      client: standalone
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0
    editable: true
